steps:
  - name: gcr.io/cloud-builders/git
    args: ["submodule", "update", "--init", "--recursive"]
  - name: gcr.io/cloud-builders/gsutil
    args: ["-m", "rsync", "-r", "-c", "-d", "-x", "\.git*", ".", "gs://code.count.ly"]